services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: market_place_api_user
      POSTGRES_PASSWORD: Postgres123
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_redis_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U market_place_api_user" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  redis:
    image: redis:8.0-M03-alpine3.21
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_URL_SIDEKIQ: "redis://redis:6379/0"
      REDIS_URL_CACHE: "redis://redis:6379/1"
    volumes:
      - ./redis_data:/data
    networks:
      - postgres_redis_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

networks:
  postgres_redis_network:
    driver: bridge
    name: postgres_redis_network
